/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#if __aarch64__
#define ARCH_AARCH64 1
#endif

#if __arm__
#define ARCH_ARM 1
#endif

#if __ppc64__
#define ARCH_PPC64LE 1
#endif

#if __i386__ || __x86_64__
#define ARCH_X86 1
#endif

#if __i386__
#define ARCH_X86_32 1
#endif

#if __x86_64__
#define ARCH_X86_64 1
#endif

#define CONFIG_16BPC 1

#define CONFIG_8BPC 1

#define CONFIG_LOG 1

#define ENDIANNESS_BIG 0

// x86_64 need NASM, but Xcode does not provide.
#if __arm__ || __aarch64__
#define HAVE_ASM 1
#endif

#define HAVE_AS_FUNC 0

// aarch64 extensions detected by meson via cc.compiles() against the assembler.
// HAVE_AS_ARCH_DIRECTIVE / AS_ARCH_LEVEL: meson probes the highest .arch level
// the assembler accepts (armv8.2-a → armv8.4-a → armv8.6-a), then appends +crc
// as a workaround for an older Clang bug (llvm/llvm-project#32220).
// On Apple Clang the target arch comes from -arch arm64, so .arch is redundant
// but harmless; the value below matches what meson would detect on Xcode 16+.
#if __aarch64__
#define HAVE_AS_ARCH_DIRECTIVE 1
#define AS_ARCH_LEVEL armv8.6-a+crc

// .arch_extension directives: meson tests each one individually.
// These let asm.S selectively ENABLE/DISABLE instruction sets per code region.
#define HAVE_AS_ARCHEXT_DOTPROD_DIRECTIVE 1
#define HAVE_AS_ARCHEXT_I8MM_DIRECTIVE 1
#define HAVE_AS_ARCHEXT_SVE_DIRECTIVE 1
#define HAVE_AS_ARCHEXT_SVE2_DIRECTIVE 1

// Instruction support: meson tests whether the actual instruction assembles.
// Runtime CPU detection (sysctlbyname) decides whether to call these paths.
// On Apple Silicon, SVE/SVE2 code compiles but is never executed at runtime
// because Apple's cpu.c reports no SVE support.
#define HAVE_DOTPROD 1
#define HAVE_I8MM 1
#define HAVE_SVE 1
#define HAVE_SVE2 1
#endif

#define HAVE_C11_GENERIC 1

#define HAVE_CLOCK_GETTIME 1

#define HAVE_DLSYM 1

#define HAVE_POSIX_MEMALIGN 1

#define HAVE_UNISTD_H 1

#define PIC 3

#define PREFIX 1

#define TRIM_DSP_FUNCTIONS 1

// Define default bit depth 8, but some template source files need to be redefined and compile twice, see `tmpl_16` folder
#ifndef BITDEPTH
#define BITDEPTH 8
#endif
